on:
  release:
    types: [created]
jobs:
  release:
    runs-on: [self-hosted, ubuntu]
    steps:
      - uses: actions/checkout@v3
      - name: nightly-rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
      - name: Build rust package
        run: |
          cd keyboard_plugin
          cargo build --release --verbose
          cd ../monitors
          cargo build --release --verbose
      - name: Build Ubuntu package
        run: |
          cd keyboard_plugin
          mkdir -p ./debian/usr
          mkdir -p ./debian/usr/lib.
          mkdir -p ./debian/usr/lib/reset
          cp ./target/release/libreset_keyboard_plugin.so ./debian/usr/lib/reset/.
          dpkg-deb --build debian
          mv debian.deb keyboard_plugin.deb
          cd ../monitors
          mkdir -p ./debian/usr
          mkdir -p ./debian/usr/lib
          mkdir -p ./debian/usr/lib/reset
          cp ./target/release/libreset_monitors.so ./debian/usr/lib/reset/.
          dpkg-deb --build debian
          mv debian.deb monitor_plugin.deb
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./keyboard_plugin/target/release/libreset_keyboard_plugin.so
            ./monitors/target/release/libreset_monitors.so
            ./keyboard_plugin/keyboard_plugin.deb
            ./monitors/monitor_plugin.deb
