on:
  release:
    types: [created]
jobs:
  release:
    runs-on: [self-hosted, arch]
    steps:
      - uses: actions/checkout@v3
      - name: nightly-rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
      - name: Build rust package
        run: |
          cd monitors
          makepkg PKGBUILD
          cd ../keyboard_plugin
          makepkg PKGBUILD
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            keyboard_plugin/reset_keyboard-${{github.ref_name}}-0-x86_64.pkg.tar.zst
            monitors/reset_monitors-${{github.ref_name}}-0-x86_64.pkg.tar.zst
